feat: Kafka external streams read from specific partitions
timeplus-io/proton pull request #206
Opened 2023-10-21 19:26 UTC by zliang-min

Closes #201 

PR checklist:
- Did you run ClangFormat ?
- Did you separate headers to a different section in existing community code base ?
- Did you surround `proton: starts/ends` for new code in existing community code base ?

Please write user-readable short description of the changes:

2023-10-21 20:04 UTC, chenziliang requested changes

2023-10-21 20:04 UTC, chenziliang commented on src/KafkaLog/KafkaWAL.cpp
> +    for (size_t i{0}; i < timestamps.size(); ++i)
for(size_t i = 0; auto t : timestamps)
  partition_timestamps.emplace_back(i++, t);

2023-10-21 20:04 UTC, chenziliang commented on src/KafkaLog/KafkaWAL.cpp
> +    std::vector<PartitionTimestampPair> partitionTimestamps{timestamps.size()};
"partition_timestamps;"
partition_timestamps.reserve(...)

2023-10-21 20:04 UTC, chenziliang commented on src/KafkaLog/KafkaWALCommon.cpp
> +    const std::vector<PartitionTimestampPair> & partitionTimestamps,
Let's pay attention to the name conventions of a variable.

2023-10-21 20:04 UTC, chenziliang commented on src/KafkaLog/KafkaWALCommon.cpp
> +    for (size_t i{0}; auto partitionTimestamp : partitionTimestamps)
Follow the convention : i = 0;

2023-10-22 15:49 UTC, chenziliang commented on src/Core/Settings.h
> +    M(Int64, kafka_fetch_wait_max_ms, 100, "When reading from Kafka, max wait time", 0) \
We will propagate these tuning knobs in a future PR

2023-10-23 15:22 UTC, merged

2023-10-27 18:30 UTC, jovezhong commented
(Jove Github Bot) added it to the current sprint.

2023-12-22 22:08 UTC, jovezhong commented
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).