Update README.md
timeplus-io/proton pull request #447
Opened 2023-12-26 07:33 UTC by yokofly

PR checklist:
- Did you run ClangFormat ?
- Did you separate headers to a different section in existing community code base ?
- Did you surround `proton: starts/ends` for new code in existing community code base ?

Please write user-readable short description of the changes:

2023-12-26 16:45 UTC, jovezhong requested changes
minor changes

2023-12-26 16:45 UTC, jovezhong commented on docs/README.md
> +Proton Documentation Site: [https://docs.timeplus.io/proton](https://docs.timeplus.com/proton)
Proton documentation: [https://docs.timeplus.io/proton](https://docs.timeplus.com/proton)

2023-12-26 16:45 UTC, jovezhong commented on docs/README.md
> +GitHub Documentation: [Proton Guide](https://github.com/timeplus-io/docs/blob/main/docs/proton.md)
Issues and PR are welcome: https://github.com/timeplus-io/docs

2023-12-27 00:35 UTC, yokofly commented
we should open some easy tasks to make people familiar this huge  codebase if u expected pr

2023-12-27 02:04 UTC, yokofly commented
open a new incognito window and cannot access https://docs.timeplus.io/proton
I am intend to switch to `.com`

2023-12-27 04:23 UTC, jovezhong approved these changes

2023-12-27 05:15 UTC, merged