add demo for the broken stream
timeplus-io/proton pull request #862
Opened 2024-11-23 01:28 UTC by gangtao

add example to show how to use EMIT PERIODIC time_interval REPEAT to monitor broken stream

2024-11-23 01:53 UTC, jovezhong requested changes
Thanks for the PR. The language in README is too casual. Need avoid grammar issues

2024-11-23 01:53 UTC, jovezhong commented on examples/broken-stream-monitor/script/iot.sql
> +WHERE count == previous_count;
=, not ==

2024-11-23 01:53 UTC, jovezhong commented on examples/broken-stream-monitor/README.md
> +This demo shows how to leverage the new feature of proton SQL to monitor a broken stream, traditionally using watermark, the stream processing will generally stop processing when there is no new even
not common to say `proton SQL`

2024-11-23 01:53 UTC, jovezhong commented on examples/broken-stream-monitor/README.md
> +This demo shows how to leverage the new feature of proton SQL to monitor a broken stream, traditionally using watermark, the stream processing will generally stop processing when there is no new even
no new event which pushes..

2024-11-23 01:53 UTC, jovezhong commented on examples/broken-stream-monitor/README.md
> +In this demo, we show how to use the new settings `EMIT PERIODIC time_interval REPEAT` to emit existing result to help monitor stream status.
EMIT is not really a setting

2024-11-23 01:53 UTC, jovezhong commented on examples/broken-stream-monitor/README.md
> +here is the steps
cannot use is and steps. Also here to Here

2024-11-23 01:53 UTC, jovezhong commented on examples/broken-stream-monitor/README.md
> +1. create a simulated data source using random stream
a stream or streams

2024-11-23 02:22 UTC, gangtao commented on examples/broken-stream-monitor/README.md
> +1. create a simulated data source using random stream
random stream is already a stream

2024-11-25 02:55 UTC, jovezhong approved these changes

2024-11-25 02:57 UTC, merged

2024-12-06 17:16 UTC, jovezhong commented
(Jove Github Bot) added it to the current sprint.

2025-01-31 21:44 UTC, jovezhong commented
(Jove Github Bot) moved this ticket out of the GitHub project(up to 1200 tickets for one project).